input-language C/C++
decl-version 2.0
var-comparability implicit

ppt ..tick():::ENTER
  ppt-type enter
  variable ARESETN
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg22_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg23_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg24_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg25_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg26_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg27_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg28_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg29_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg30_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg31_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg32_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg33_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg34_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg35_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg36_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable M_AXI_AWADDR_wire
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable M_AXI_AWADDR_INT
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable shadow_M_AXI_AWADDR
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable shadow_M_AXI_AWADDR_INT
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable shadow_M_AXI_AWADDR_wire
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable delay
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 

ppt ..tick():::EXIT0
  ppt-type subexit
  variable ARESETN
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg22_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg23_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg24_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg25_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg26_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg27_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg28_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg29_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg30_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg31_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg32_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg33_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg34_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg35_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable reg36_w_config
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable M_AXI_AWADDR_wire
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable M_AXI_AWADDR_INT
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable shadow_M_AXI_AWADDR
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable shadow_M_AXI_AWADDR_INT
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable shadow_M_AXI_AWADDR_wire
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
  variable delay
	var-kind variable
	rep-type int
	dec-type int
	comparability 1 
