src = 'M_AXI_AWADDR_wire'

nts = ['ACLK', 'ARESETN', 'AR_ADDR_VALID', 'AR_ADDR_VALID_FLAG', 'AR_CH_DIS', 'AR_CH_EN', 'AR_EN_RST', 'AR_HIGH_ADDR', 'AR_ILLEGAL_REQ', 'AR_ILL_TRANS_FIL_PTR', 'AR_ILL_TRANS_SRV_PTR', 'AR_STATE', 'AW_EN_RST', 'INTR_LINE_R', 'INTR_LINE_W', 'M_AXI_ARADDR', 'M_AXI_ARADDR_INT', 'M_AXI_ARADDR_wire', 'M_AXI_ARBURST', 'M_AXI_ARBURST_INT', 'M_AXI_ARBURST_wire', 'M_AXI_ARCACHE', 'M_AXI_ARCACHE_INT', 'M_AXI_ARCACHE_wire', 'M_AXI_ARID', 'M_AXI_ARID_INT', 'M_AXI_ARID_wire', 'M_AXI_ARLEN', 'M_AXI_ARLEN_INT', 'M_AXI_ARLEN_wire', 'M_AXI_ARLOCK', 'M_AXI_ARLOCK_INT', 'M_AXI_ARLOCK_wire', 'M_AXI_ARPROT', 'M_AXI_ARPROT_INT', 'M_AXI_ARPROT_wire', 'M_AXI_ARQOS', 'M_AXI_ARQOS_INT', 'M_AXI_ARQOS_wire', 'M_AXI_ARREADY', 'M_AXI_ARREADY_wire', 'M_AXI_ARSIZE', 'M_AXI_ARSIZE_INT', 'M_AXI_ARSIZE_wire', 'M_AXI_ARUSER', 'M_AXI_ARUSER_INT', 'M_AXI_ARUSER_wire', 'M_AXI_ARVALID', 'M_AXI_ARVALID_wire', 'M_AXI_AWADDR', 'M_AXI_AWBURST', 'M_AXI_AWBURST_INT', 'M_AXI_AWBURST_wire', 'M_AXI_AWCACHE', 'M_AXI_AWCACHE_wire', 'M_AXI_AWID', 'M_AXI_AWID_INT', 'M_AXI_AWID_wire', 'M_AXI_AWLEN', 'M_AXI_AWLEN_wire', 'M_AXI_AWLOCK', 'M_AXI_AWLOCK_INT', 'M_AXI_AWLOCK_wire', 'M_AXI_AWPROT', 'M_AXI_AWPROT_wire', 'M_AXI_AWQOS', 'M_AXI_AWQOS_wire', 'M_AXI_AWREADY', 'M_AXI_AWSIZE', 'M_AXI_AWSIZE_wire', 'M_AXI_AWUSER', 'M_AXI_AWUSER_INT', 'M_AXI_AWUSER_wire', 'M_AXI_AWVALID', 'M_AXI_BID', 'M_AXI_BID_wire', 'M_AXI_BREADY', 'M_AXI_BREADY_wire', 'M_AXI_BRESP', 'M_AXI_BRESP_wire', 'M_AXI_BUSER', 'M_AXI_BUSER_wire', 'M_AXI_BVALID', 'M_AXI_RDATA', 'M_AXI_RDATA_wire', 'M_AXI_RID', 'M_AXI_RID_wire', 'M_AXI_RLAST', 'M_AXI_RLAST_wire', 'M_AXI_RREADY', 'M_AXI_RREADY_wire', 'M_AXI_RRESP', 'M_AXI_RRESP_wire', 'M_AXI_RUSER', 'M_AXI_RUSER_wire', 'M_AXI_RVALID', 'M_AXI_RVALID_wire', 'M_AXI_WDATA', 'M_AXI_WDATA_wire', 'M_AXI_WLAST', 'M_AXI_WREADY', 'M_AXI_WREADY_wire', 'M_AXI_WSTRB', 'M_AXI_WSTRB_wire', 'M_AXI_WUSER', 'M_AXI_WUSER_wire', 'M_AXI_WVALID', 'R_STATE', 'S_AXI_CTRL_ARADDR', 'S_AXI_CTRL_ARPROT', 'S_AXI_CTRL_ARREADY', 'S_AXI_CTRL_ARVALID', 'S_AXI_CTRL_AWADDR', 'S_AXI_CTRL_AWPROT', 'S_AXI_CTRL_AWREADY', 'S_AXI_CTRL_AWVALID', 'S_AXI_CTRL_BREADY', 'S_AXI_CTRL_BRESP', 'S_AXI_CTRL_BVALID', 'S_AXI_CTRL_RDATA', 'S_AXI_CTRL_RREADY', 'S_AXI_CTRL_RRESP', 'S_AXI_CTRL_RVALID', 'S_AXI_CTRL_WDATA', 'S_AXI_CTRL_WREADY', 'S_AXI_CTRL_WSTRB', 'S_AXI_CTRL_WVALID', 'aw_en', 'axi_araddr', 'axi_arready', 'axi_awaddr', 'axi_awready', 'axi_bresp', 'axi_bvalid', 'axi_rdata', 'axi_rresp', 'axi_rvalid', 'axi_wready', 'data_val_wire', 'i_config', 'internal_data', 'o_data', 'r_base_addr_wire', 'r_burst_len_wire', 'r_displ_wire', 'r_done_wire', 'r_max_outs_wire', 'r_num_trans_wire', 'r_phase_wire', 'r_start_wire', 'reg00_config', 'reg01_config', 'reg03_r_anomaly', 'reg06_r_config', 'reg07_r_config', 'reg08_r_config', 'reg09_r_config', 'reg0_config', 'reg10_r_config', 'reg11_r_config', 'reg12_r_config', 'reg13_r_config', 'reg14_r_config', 'reg15_r_config', 'reg16_r_config', 'reg17_r_config', 'reg18_r_config', 'reg19_r_config', 'reg20_r_config', 'reg21_r_config', 'reg22_w_config', 'reg23_w_config', 'reg24_w_config', 'reg25_w_config', 'reg26_w_config', 'reg27_w_config', 'reg28_w_config', 'reg29_w_config', 'reg30_w_config', 'reg31_w_config', 'reg32_w_config', 'reg33_w_config', 'reg34_w_config', 'reg35_w_config', 'reg36_w_config', 'reg37_w_config', 'regXX_rden', 'regXX_wren', 'reset_wire', 'w_base_addr_wire', 'w_burst_len_wire', 'w_displ_wire', 'w_done_wire', 'w_max_outs_wire', 'w_num_trans_wire', 'w_phase_wire', 'w_start_wire']

## ref property

# CLT_TR4_W_B_TO_SERVE: assert iflow (
# W_B_TO_SERVE
# =/=> 
# M_AXI_AWADDR_wire
# unless
# (ARESETN != 0)
# );

as_file = open("iACW_sps.as","w")
indent = "    "
count = 0
for nt in nts:
	as_file.write("autogenerated_" + str(count).zfill(3) + "_" + src + "_to_" + nt + ": assert iflow (\n")
	as_file.write(indent + src + "\n")
	as_file.write(indent + "=/=>" + "\n")
	as_file.write(indent + nt + "\n")
	as_file.write(");\n\n")
	count = count + 1

